# * ***********************************************
# * For Live Testing
# * ***********************************************

# base route
get https://warframe-mods-api.onrender.com
###

# mods getAll route
get https://warframe-mods-api.onrender.com/mods
###

# mods getSingle route
get https://warframe-mods-api.onrender.com/mods/6a11c84aa38b552ba7ddee06
###

# equip getAll
get https://warframe-mods-api.onrender.com/equip
###

# equip getSingle
get https://warframe-mods-api.onrender.com/equip/6a11c687a38b552ba7ddedec
###

# ---------- POST requests ----------
# testing post with equip type that exists
post https://warframe-mods-api.onrender.com/mods
Content-Type: application/json

{
    "_id": "6a11f5652b6c4d95a514185a",
    "name": "Afterburner",
    "copies": 1,
    "c_rank": 0,
    "max_rank": 3,
    "equip_id": "Elytron",
    "rarity": "Rare",
    "in_set": "no"
}
###

# testing post with equip that doesn't exist
post https://warframe-mods-api.onrender.com/mods
Content-Type: application/json

{
    "_id": "6a11f5652b6c4d95a514185a",
    "name": "Afterburner",
    "copies": 1,
    "c_rank": 0,
    "max_rank": 3,
    "equip_id": "asdf",
    "rarity": "Rare",
    "in_set": "no"
}
###

# equip create without ID
post https://warframe-mods-api.onrender.com/equip
Content-Type: application/json

{
    "type_name":"asdf"
}
###

# ---------- PUT requests ----------
# mod put request
put https://warframe-mods-api.onrender.com/mods/6a11f5652b6c4d95a514185a
Content-Type: application/json

{
    "name": "Afterburner-testput"
}
###

# ---------- DELETE requests ----------
DELETE https://warframe-mods-api.onrender.com/mods/6a11f5652b6c4d95a514185a
###