# * ***********************************************
# * For Local Testing
# * ***********************************************

# base route
get http://localhost:3000
###

# mods getAll route
get http://localhost:3000/mods
###